# -*- coding: utf-8 -*-
"""titanicdata.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VfkmbFs3GCgvm6SF5wv0GVgiFE-PVSX9
"""

import pandas as pd

df = pd.read_csv('/content/archive (1).zip')

df

df = pd.read_csv('/content/archive.zip')

df

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/

!kaggle kernels pull saikaislam/notebook111effdaee

import zipfile
zip_ref = zipfile.ZipFile('/content/archive (1).zip', 'r')
zip_ref.extractall('/content')
zip_ref.close()

df = pd.read_csv('/content/shopping_behavior_updated (1).csv')

df